# Official Dockware Image
# Tag: {{ orca.tag }}
# Copyright 2023 dasistweb GmbH
#
FROM {{ base_image }}
LABEL title="Dockware {{ orca.image }}:{{ orca.tag }}" \
      version="{{version}}" \
      maintainer="dasistweb GmbH"

USER root


{% block assets_install %}{% endblock %}

{% block image_variables %}{% endblock %}
#make sure we have this variables always set and not overwritten in image_variables block
ENV PHP_VERSION {{php.default_version}}
ENV APACHE_DOCROOT {{ apache.docroot }}
{% if node.default_version is defined %}
ENV NODE_VERSION {{ node.default_version }}
ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/v$NODE_VERSION/bin:$PATH
{% endif %}
ENV TZ Europe/Berlin
ENV SW_TASKS_ENABLED 0
ENV COMPOSER_VERSION not-set
ENV SSH_USER not-set
ENV SSH_PWD not-set
ENV FILEBEAT_ENABLED 0
ENV VERBOSE 0
ENV BASH_ENV /var/www/.bashrc


#starting the mainlayer
RUN date >/build-date.txt \
{% block image_variables_export %}{% endblock %}

{% block image_components %}
    #just end the current layer
    && echo "" \
{% endblock %}

#cleaning up
&& apt-get clean all \
&& rm -rf /var/lib/apt/lists/* /var/cache/apt/* \

&& chown 33:33 -R /var/www/html \
    # this is necessary so that our user can
    # change the default nvm node version
    # otherwise the persisted node version switch would not work!
    {% block chown_nvm %}
      && chown 33:33 /var/www/.nvm -R \
    {% endblock %}
    && rm -rf /tmp/*



## ***********************************************************************
## SWITCH TO NORMAL USER (NOT ROOT ANYMORE!)
## everything down here is now done as our www-data / dockware user
## just like you would do it manually in the container
## ***********************************************************************
USER {{ ssh.user.name }}

# make the apache folder the working directory
WORKDIR /var/www/html



## ***********************************************************************
##  POST BUILD
## ***********************************************************************

#keep the entrypoint as last command so that a change in it does not trigger a full rebuild
ADD entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
