# Official Dockware Image
# Tag: {{ orca.tag }}
# Copyright 2023 dasistweb GmbH
#
FROM {{ base_image }}
LABEL title="Dockware {{ orca.image }}:{{ orca.tag }}" \
      version="{{version}}" \
      maintainer="dasistweb GmbH"

USER root

ADD entrypoint.sh /entrypoint.sh


{% block assets_install %}{% endblock %}

{% block image_variables %}{% endblock %}


#starting the mainlayer
RUN date >/build-date.txt \
{% block image_variables_export %}{% endblock %}

{% block image_components %}
    && echo "" \ #just end the current layer
{% endblock %}

#make sure we uninstall all unneeded stuff
{% block uninstall_components %}
    && echo "" \
{% endblock %}

&& chown 33:33 -R /var/www/html && \
    # this is necessary so that our user can
    # change the default nvm node version
    # otherwise the persisted node version switch would not work!
    chown 33:33 /var/www/.nvm -R \
    && rm -rf /tmp/*



## ***********************************************************************
## SWITCH TO NORMAL USER (NOT ROOT ANYMORE!)
## everything down here is now done as our www-data / dockware user
## just like you would do it manually in the container
## ***********************************************************************
USER {{ ssh.user.name }}

# make the apache folder the working directory
WORKDIR /var/www/html



## ***********************************************************************
##  POST BUILD
## ***********************************************************************

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
