{% extends "variants/essentials/Dockerfile.base.sh.twig" %}


{%  block shopware_cli %}{% endblock %}
{#  is needed as otherwise w get a error as the dir does not exist #}
{% block chown_nvm %}{% endblock %}
{% block nvm_bash_rc %}{% endblock %}