{% extends "template/Dockerfile.global.sh.twig" %}


{% block image_components %}
    #make sure for the whole installation xdebug is off for performance
    && sh /var/www/scripts/bin/xdebug_disable.sh \

    {% block shopware %}
    {% include 'template/components/shopware/shopware5/install.sh.twig' with {'download_url': shopware.download_url 'db_host': db.host, 'db_user' : db.user, 'db_database' : db.database, 'db_pwd' : db.pwd, 'demo_data' : true } %}
    {% endblock %}
{% endblock %}


{% block assets_install %}
{{ parent() }}
COPY  ./assets/shopware5/config.php /tmp/shopware5-config.php
{% endblock %}




