.PHONY: help
.DEFAULT_GOAL := help


PHP_VERSION_CURRENT=$(shell php -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;')


help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'


permission-repair: ## repairs the general file permissions
	sudo chown -R www-data:www-data /var/www/html/*
	sudo chmod -R 775 /var/www/html
	cd /var/www/scripts/shopware6 && php create_jwt.php
	cd /var/www/html/config/jwt && sudo chown www-data:www-data *

restart-fpm:
	service php$(PHP_VERSION_CURRENT)-fpm stop
	service php$(PHP_VERSION_CURRENT)-fpm start
	export PHP_VERSION=$(version)
	service apache2 restart
	update-alternatives --set php /usr/bin/php$(PHP_VERSION_CURRENT)
	@# ---------------------------------------------------------------------------------------
	php -v
