{% extends "template/assets/assets/scripts/makefile.twig" %}


{% block watcher_storefront %}

{% endblock %}


{% block watcher_admin %}

{% endblock %}

{% block build_admin %}
{% endblock %}


{% block contribute_pull %}

{% endblock %}
