{% extends "variants/dev/Dockerfile.base.sh.twig" %}


{% block image_variables_sw_currency %}
{% endblock %}


{% block assets_install_shopware6 %}
{% endblock %}


{% block shopware %}
RUN rm -rf /var/www/html/* \
    && wget {{ shopware.download_url }} -qq -O /var/www/shopware.zip \
    && unzip -q /var/www/shopware.zip -d /var/www/html \
    && rm -rf /var/www/shopware.zip

{% include 'template/components/shopware/shopware5/install.sh.twig' with {'db_host': db.host, 'db_user' : db.user, 'db_database' : db.database, 'db_pwd' : db.pwd, 'demo_data' : true } %}

{% endblock %}

{% block shopware_tools_dev_cli %}
{% endblock %}