{% extends "template/Dockerfile.global.sh.twig" %}

{% block image_variables %}
{{ parent() }}
ENV SW_CURRENCY 'not-set'
ENV SW_API_ACCESS_KEY 'not-set'
{% endblock %}

{% block assets_install %}
COPY ./assets/shopware6/DockwareSamplePlugin /var/www/html/custom/plugins/DockwareSamplePlugin
COPY ./assets/shopware6/files /var/www/scripts/shopware6

COPY ./assets/scripts/cron /var/www/scripts/cron
{% endblock %}

{% block image_variables_export %}
{{ parent() }}
&& echo "export SW_API_ACCESS_KEY=${SW_API_ACCESS_KEY}" >> /etc/profile \
&& echo "export SW_CURRENCY=${SW_CURRENCY}" >> /etc/profile \
{% endblock %}

{% block image_components %}
    #make sure for the whole installation xdebug is off for performance
    && sh /var/www/scripts/bin/xdebug_disable.sh \
    #make sure the installation runs also in default php version
    && echo "DOCKWARE: switching to PHP {{php.default_version}}..." \
    && cd /var/www && make switch-php version={{php.default_version}}  && cd /var/www/html \
    {#  if node.default_version is defined %#}
        && echo "DOCKWARE: switching to NODE {{node.default_version}}..." \
        && nvm use {{ node.default_version }} \
        && nvm alias default {{ node.default_version }}  \
    {#   endif %#}
     {%  if shopware.version > 6.4 %}
        {% include 'template/components/shopware/shopware6/install_flex.sh.twig' with { 'pwd' : db.pwd } %}
    {%  else %}
        {% include 'template/components/shopware/shopware6/install_6.4.sh.twig' with { 'pwd' : db.pwd } %}
    {% endif %}

    {% block shopware_dev %}{% endblock %}
{% endblock %}
