{% extends "variants/dev/Dockerfile.base.sh.twig" %}


{% block image_variables_sw_currency %}
{% endblock %}


{% block assets_install_shopware6 %}
{% endblock %}

{% block components_packagers_composer %}
    USER www-data
    # install composer (with the commit hash we make sure that we don't install composer 2.0.0 which does not work for all sw6 installations)
    RUN  curl -sS https://getcomposer.org/installer | php -- --install-dir=/tmp --version=1.10.16 --quiet \
    # prepare "global" composer directory for www-data
    && mkdir -p /var/www/.composer \
    && export COMPOSER_HOME="/var/www/.composer" \
    && chmod 755 /tmp/composer.phar
    USER root
    RUN  mv /tmp/composer.phar /usr/local/bin/composer \
     # install prestissimo for parallel dependency installation (https://github.com/hirak/prestissimo)
    && cd /var/www/.composer && composer require hirak/prestissimo \
{% endblock %}


{% block shopware %}
RUN rm -rf /var/www/html/* \
    && wget {{ shopware.download_url }} -qq -O /var/www/shopware.zip \
    && sudo -u www-data unzip -q /var/www/shopware.zip -d /var/www/html \
    && rm -rf /var/www/shopware.zip

{% include 'template/components/shopware/shopware5/install.sh.twig' with {'db_host': db.host, 'db_user' : db.user, 'db_database' : db.database, 'db_pwd' : db.pwd, 'demo_data' : true } %}

{% endblock %}

