{% extends "variants/essentials_play/Dockerfile.base.sh.twig" %}

{% block assets_install %}
COPY ./config/mysql/my-5.7.cnf /tmp/my.cnf
{% endblock %}



{% block image_components %}
{% include 'template/components/mysql/install.sh.twig' with { 'pwd' : db.pwd } %}

# Install composer 1
   &&  echo "DOCKWARE: switching to co mposer 1..." \
   && sudo composer self-update --1 \


{{  parent() }}
{% endblock %}