.PHONY: help
.DEFAULT_GOAL := help


help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

# ---------------------------------------------------------------------------------------------
{% block watcher_storefront %}
watch-storefront: ## starts watcher for storefront at {{ shopware.url }}
	@echo "RequestHeader add hot-reload-mode "1"" > /var/www/html/.htaccess.watch
	cd /var/www/html && ./bin/build-storefront.sh
	cd /var/www/html && php bin/console theme:dump
	cd /var/www/html && PROJECT_ROOT=/var/www/html APP_URL={{ shopware.url }} ESLINT_DISABLE=true npm --prefix /var/www/html/vendor/shopware/storefront/Resources/app/storefront run hot

stop-watch-storefront: ## Reverts everything back to normal operation
	@rm -rf /var/www/html/.htaccess.watch

# ---------------------------------------------------------------------------------------------
{% endblock %}

{% block watcher_admin %}
watch-admin: ## starts watcher for admin at {{ shopware.url }}:8888
	cd /var/www/html && ./bin/build-administration.sh
	cd /var/www/html && php bin/console bundle:dump
	cd /var/www/html && PROJECT_ROOT=/var/www/html APP_ENV=dev PORT=8888 HOST=0.0.0.0 ENV_FILE=/var/www/html/.env ESLINT_DISABLE=true npm run --prefix /var/www/html/vendor/shopware/administration/Resources/app/administration dev -- http://0.0.0.0
{% endblock %}

{% block contribute_pull %}
{% endblock %}
