{% extends "variants/base/Dockerfile.base.sh.twig" %}

{% block assets_install %}
{{ parent() }}
COPY ./config/tideways/tideways.ini /tmp/20-tideways.ini
COPY ./config/php/xdebug-2.ini /tmp/xdebug-2.ini
COPY ./config/php/xdebug-3.ini /tmp/xdebug-3.ini

COPY ./config/tideways/tideways-daemon /etc/default/tideways-daemon
COPY ./assets/tideways/tideways-daemon /etc/init.d/tideways-daemon
{% endblock %}

{% block image_variables_main %}
{{ parent() }}
ENV XDEBUG_REMOTE_HOST "host.docker.internal"
ENV XDEBUG_CONFIG "idekey=PHPSTORM"
ENV PHP_IDE_CONFIG "serverName=localhost"
ENV XDEBUG_ENABLED 0

ENV TIDEWAYS_KEY not-set
ENV TIDEWAYS_ENV production
ENV TIDEWAYS_SERVICE web
{% endblock %}

{% block image_variables_export %}
&& echo "export XDEBUG_ENABLED=${XDEBUG_ENABLED}" >> /etc/profile \
 && echo "export XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}" >> /etc/profile \
 && echo "export XDEBUG_CONFIG=${XDEBUG_CONFIG}" >> /etc/profile \
 && echo "export PHP_IDE_CONFIG=${PHP_IDE_CONFIG}" >> /etc/profile \

  && echo "export TIDEWAYS_KEY=${TIDEWAYS_KEY}" >> /etc/profile \
 && echo "export TIDEWAYS_ENV=${TIDEWAYS_ENV}" >> /etc/profile \
 && echo "export TIDEWAYS_SERVICE=${TIDEWAYS_SERVICE}" >> /etc/profile \
{% endblock %}

{%  block additional %}


{% block components_nvm %}
&& ls -la \
    && mkdir "/var/www/.nvm" \
    && export NVM_DIR="/var/www/.nvm" \
    # -----------------------------------------------------------------------------------------
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash \
    # -----------------------------------------------------------------------------------------
    && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" \
    && [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  \
    # -----------------------------------------------------------------------------------------

    {% for version in node.versions %}
    && nvm install {{ version }} \
    # -----------------------------------------------------------------------------------------
    # we have to install yarn in additional node versions
    # otherwise it won't be found after a nvm switch
    && nvm use {{version}} && npm install -g yarn \
    {% endfor %}
    # -----------------------------------------------------------------------------------------
    && nvm use {{ node.default_version }} \
    && nvm alias default {{ node.default_version }}  \
    # -----------------------------------------------------------------------------------------
{% endblock %}

{% block components_node %}
    # -----------------------------------------------------------
    # we have to reload the correct nvm version otherwise this would destroy it
    && export NVM_DIR="/var/www/.nvm" \
    && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" \
    && [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  \
    && nvm use {{ node.default_version }} \
    # -----------------------------------------------------------
    && mkdir /var/www/.npm \
    && npm config set cache /var/www/.npm \
    && chown 33:33 /var/www/.npm \
{% endblock %}

{% block components_grunt %}
    # navigate to another folder outside shopware to avoid this error: npm ERR! Tracker "idealTree" already exists
    && cd /var/www && npm install -g grunt-cli \
    && cd /var/www && npm install grunt --save-dev \
{% endblock %}

{% block components_packagers_yarn %}
    && npm install -g --no-install-recommends yarn \
    && chown -R www-data:www-data /var/www/.composer \
{% endblock %}

##install xdebug
{% include 'template/components/xdebug/base.sh.twig' %}

##install tideways
&& sudo echo 'deb https://packages.tideways.com/apt-packages-main any-version main' | sudo tee /etc/apt/sources.list.d/tideways.list \
    && sudo wget -qO - https://packages.tideways.com/key.gpg | sudo apt-key add - \
    && sudo apt-get -y update  \
    && sudo apt-get -y install tideways-php tideways-daemon  \
    {% for key,value in php.versions %}
    {%  if value.active == true %}
    && cat /tmp/20-tideways.ini >| /etc/php/{{ key }}/fpm/conf.d/20-tideways.ini \
    && cat /tmp/20-tideways.ini >| /etc/php/{{ key }}/cli/conf.d/20-tideways.ini \
    {% endif %}
    {% endfor %}
    #clean up layer
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/* \
    && sudo chmod 0755 /etc/init.d/tideways-daemon \

{% endblock %}