{% extends "template/assets/assets/scripts/makefile.twig" %}


{% block essentials_download %}
# ---------------------------------------------------------------------------------------------
shopware: ##1 Setup the provided Shopware version. Use: make shopware version=6.5.6.0
ifndef version
	$(warning Please provide the version of Shopware!)
	@exit 1
else
	sudo rm -rf /var/www/html/*
	sudo rm -rf /var/www/tmp
	cd /var/www && composer create-project shopware/production --no-interaction tmp
	cp -a /var/www/tmp/. /var/www/html
	rm -rf /var/www/tmp
	cd /var/www/html && composer req shopware/core:$(version) shopware/administration:$(version) shopware/elasticsearch:$(version) shopware/storefront:$(version) -W
endif

download: ##1 Downloads a provided ZIP URL, such as Shopware versions. Use: make download url=(https://......shopware6.zip)
ifndef url
	$(warning Please provide the URL to the Shopware ZIP file!)
	@exit 1
else
	sudo rm -rf /var/www/html/*
	sudo wget $(url) -qq -O /var/www/shopware.zip
	sudo -u www-data sh -c 'unzip -q /var/www/shopware.zip -d /var/www/html'
	sudo rm -rf /var/www/shopware.zip
endif
{% endblock %}

{% block contribute_pull %}
{% endblock %}
