name: On Push

on:
  push:
    branches:
      - master

jobs:
  on-push:
    name: On Push
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Dependencies
        run: make install

      - name: ORCA Generate
        run: make generate

      - name: Generate Workflows
        run: cd build && make generate-actions

      - name: Archive DIST Files
        run: cd build && make generate-dist version=master

      - name: Commit and Push
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git remote add github "https://${{ secrets.GIT_WORKFLOW_USER }}:${{ secrets.GIT_WORKFLOW_PAT }}@github.com/$GITHUB_REPOSITORY.git"
          git add ./.dist/versions/master
          git add ./.github/workflows
          if [[ -z $(git status -s) ]]
          then
            echo "No changes found!"
          else
            git commit -m "Auto Commit from Github Workflow"
            git push github HEAD:${GITHUB_REF}
          fi

