name: Release Shopware 6.6.*

on:
  workflow_dispatch:

jobs:
  on-push:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - shopware: '6.6.7.0'
            latest: true
          - shopware: '6.6.6.1'
            latest: false
          - shopware: '6.6.6.0'
            latest: false
          - shopware: '6.6.5.0'
            latest: false
          - shopware: '6.6.1.0'
            latest: false
          - shopware: '6.6.0.2'
            latest: false
          - shopware: '6.6.0.1'
            latest: false
          - shopware: '6.6.0.0'
            latest: false
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Release, Shopware ${{ matrix.shopware }}
        uses: ./.github/actions/circleci
        with:
          # -------------------------------------------
          SW_VERSION: ${{ matrix.shopware }}
          SET_LATEST: ${{ matrix.latest }}
          # -------------------------------------------
          CIRCLECI_KEY: ${{ secrets.CIRCLE_CI_TOKEN }}
          # -------------------------------------------

