name: Release Shopware Image
run-name: Shopware ${{ github.event.inputs.swVersion }}, setLatest ${{ github.event.inputs.setLatest }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Which version of the image to build'
        required: true
        default: 'play'
      tag:
        description: 'Which tag of the image to build'
        required: true
        default: 'latest'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/${{ github.event.inputs.version }}
  CONTEXT_PATH: .dist/versions/${{ github.ref_name }}/${{ github.event.inputs.version }}/${{ github.event.inputs.tag }}

jobs:
  on-push:
    name: Release Image
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: make install

      - name: ORCA Generate
        run: make build image=${{ github.events.inputs.version }} tag=${{ githun.events.inputs.tag }}

      - name: Archive DIST Files
        run: cd build && make generate-dist version=master

      - name: Log in to the container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker buildx for cache
        uses: docker/setup-buildx-action@v3.5.0

      - name: Repository name to lowercase
        run: |
          echo "FULL_LOWERCASE_NAME=${REGISTRY}/${IMAGE_NAME@L}" >> "${GITHUB_ENV}"

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6.5.0
        with:
          platforms: linux/amd64
          outputs: type=image,name=${{ env.FULL_LOWERCASE_NAME }},push-by-digest=true,name-canonical=true,push=true
          context: ${{ env.CONTEXT_PATH }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.FULL_LOWERCASE_NAME }}:buildcache-amd64
          cache-to: type=registry,ref=${{ env.FULL_LOWERCASE_NAME }}:buildcache-amd64,mode=max