name: Release Shopware 6.5.*

on:
  workflow_dispatch:

jobs:
  on-push:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - shopware: '6.5.8.18'
            latest: false
          - shopware: '6.5.8.15'
            latest: false
          - shopware: '6.5.8.14'
            latest: false
          - shopware: '6.5.8.13'
            latest: false
          - shopware: '6.5.8.12'
            latest: false
          - shopware: '6.5.8.11'
            latest: false
          - shopware: '6.5.8.10'
            latest: false
          - shopware: '6.5.8.9'
            latest: false
          - shopware: '6.5.8.8'
            latest: false
          - shopware: '6.5.8.7'
            latest: false
          - shopware: '6.5.8.6'
            latest: false
          - shopware: '6.5.8.5'
            latest: false
          - shopware: '6.5.8.4'
            latest: false
          - shopware: '6.5.8.3'
            latest: false
          - shopware: '6.5.8.2'
            latest: false
          - shopware: '6.5.8.1'
            latest: false
          - shopware: '6.5.8.0'
            latest: false
          - shopware: '6.5.7.4'
            latest: false
          - shopware: '6.5.7.3'
            latest: false
          - shopware: '6.5.7.2'
            latest: false
          - shopware: '6.5.7.1'
            latest: false
          - shopware: '6.5.7.0'
            latest: false
          - shopware: '6.5.6.1'
            latest: false
          - shopware: '6.5.6.0'
            latest: false
          - shopware: '6.5.5.2'
            latest: false
          - shopware: '6.5.5.1'
            latest: false
          - shopware: '6.5.5.0'
            latest: false
          - shopware: '6.5.4.1'
            latest: false
          - shopware: '6.5.4.0'
            latest: false
          - shopware: '6.5.3.3'
            latest: false
          - shopware: '6.5.3.2'
            latest: false
          - shopware: '6.5.3.1'
            latest: false
          - shopware: '6.5.3.0'
            latest: false
          - shopware: '6.5.2.1'
            latest: false
          - shopware: '6.5.2.0'
            latest: false
          - shopware: '6.5.1.1'
            latest: false
          - shopware: '6.5.1.0'
            latest: false
          - shopware: '6.5.0.0'
            latest: false
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Release, Shopware ${{ matrix.shopware }}
        uses: ./.github/actions/circleci
        with:
          # -------------------------------------------
          SW_VERSION: ${{ matrix.shopware }}
          SET_LATEST: ${{ matrix.latest }}
          # -------------------------------------------
          CIRCLECI_KEY: ${{ secrets.CIRCLE_CI_TOKEN }}
          # -------------------------------------------

