name: Release Shopware 6.5.*

on:
  workflow_dispatch:

jobs:
  on-push:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - shopware: '6.5.3.3'
            latest: true
          - shopware: '6.5.3.2'
            latest: false
          - shopware: '6.5.3.1'
            latest: false
          - shopware: '6.5.3.0'
            latest: false
          - shopware: '6.5.2.1'
            latest: false
          - shopware: '6.5.2.0'
            latest: false
          - shopware: '6.5.1.1'
            latest: false
          - shopware: '6.5.1.0'
            latest: false
          - shopware: '6.5.0.0'
            latest: false
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Release, Shopware ${{ matrix.shopware }}
        uses: ./.github/actions/circleci
        with:
          # -------------------------------------------
          SW_VERSION: ${{ matrix.shopware }}
          SET_LATEST: ${{ matrix.latest }}
          # -------------------------------------------
          CIRCLECI_KEY: ${{ secrets.CIRCLE_CI_TOKEN }}
          # -------------------------------------------

